name: cloudflared

on: [workflow_dispatch]

jobs:
  install-dependencies:
    uses: ./.github/workflows/install-dependencies.yml

  run-cloudflared:
    needs: install-dependencies
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup RDP
        run: ./scripts/setup-rdp.ps1 -Password ${{ secrets.PASSWORD }}
      - name: Start cloudflared
        run: ./scripts/start-cloudflared.ps1 -TgToken ${{ secrets.TG_TOKEN }} -TgChatId ${{ secrets.TG_CHAT_ID }}