name: NGROK

on: [workflow_dispatch]

jobs:
  install-dependencies:
    uses: ./.github/workflows/install-dependencies.yml

  run-ngrok:
    needs: install-dependencies
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup RDP
        run: ./scripts/setup-rdp.ps1 -Password ${{ secrets.PASSWORD }}
      - name: Start NGROK
        run: ./scripts/start-ngrok.ps1 -NgrokAuthToken ${{ secrets.NGROK_AUTH_TOKEN }} -NgrokRegion ${{ secrets.NGROK_REGION }} -TgToken ${{ secrets.TG_TOKEN }} -TgChatId ${{ secrets.TG_CHAT_ID }}